### ISSUE TITLE
Testing Github Discussions

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/OpenScience#1]
https://github.com/SAEL-SWFSC/OpenScience/blob/0ee5d402a91d3e00699a854556d012f5c1fe9357/content/exercises/PAM-SI-Mtg-MeetingNotes.qmd#L5-L9

Maybe we can test this during Monday's meeting?

**Comment by rebecca-vanhoeck** [comment]
That's a great idea. I think Discussions could be really useful!
