### ISSUE TITLE
Wrong Section Header 

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/OpenScience#13]
https://github.com/SAEL-SWFSC/OpenScience/blob/305ca07a6653171fef47b6eae48511b4284951ce/_quarto.yml#L41-L42

The text for this section header is not showing up correctly, the document is also not rendering. I think it should be as follows 

` - section: content/CoWorking.qmd`
`text: Co Working`

**Comment by shannonrankin** [comment]
Oh, that was a strange one.... I tried fifty times on my side, and then realized that the changes I made on my local were not going to github (and I did all I know to do to make sure they were merged). Ultimately, I had to force the change directly on the Github, and now it seems to be right. 

So very, very strange....

Thanks!

**Comment by shannonrankin** [comment]
Oh, that was a strange one.... I tried fifty times on my side, and then
realized that the changes I made on my local were not going to github (and
I did all I know to do to make sure they were merged). Ultimately, I had to
force the change directly on the Github, and now it seems to be right.

So very, very strange....

Thanks!
