### ISSUE TITLE
Issue Template Example

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/OpenScience#17]
https://github.com/SAEL-SWFSC/OpenScience/blob/96084c743cead9a2144bdfdf92037cfc8fe488bb/content/issues.qmd#L51

@shannonrankin I have an example of issue templates if you are interested in sharing it. We don't really use these but its a good example to show https://github.com/Kourtney-Burger/Inventree/issues. Click on 'New Issue' and you should see the different templates I made for our inventory updates

**Comment by shannonrankin** [comment]
Great, added this link. At some point in the future we can build this out into a full example (but I don't want to go that deep this week!).
