### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by Kourtney-Burger** [SAEL-SWFSC/OpenScience#18]
https://github.com/SAEL-SWFSC/OpenScience/blob/96084c743cead9a2144bdfdf92037cfc8fe488bb/content/issues.qmd#L70

The jpg image at the end of this line is not rendering correctly

**Comment by shannonrankin** [comment]
Fixed, stupid JPG jpg thing, which can only be fixed directly in repo (have not been successful changing those locally and then pushing up). Thanks!
