### ISSUE TITLE
Review "add bio" instruction

### ISSUE THREAD

**Issue by rebecca-vanhoeck** [SAEL-SWFSC/OpenScience#3]
Hi @shannonrankin and @Kourtney-Burger - 

Could one of you review the first two steps I added for the "Add bio" instructions? I made a few mistakes when trying to edit my own bio and want to help other avoid them. I think we will need to do some basic instruction of the mechanics of github - what push/pull/commit/etc. all mean and when to do them.

**Comment by shannonrankin** [comment]
I don't see any changes?  I"m available this morning if a quick conversation will help-- you can reach me via google chat or just sent a google invite. Or, check that the changes you made were rendered.

**Comment by Kourtney-Burger** [comment]
Hi Becca and Shannon, it looks like there's some confusion with the content qmd files. Originally we had 'PAM-SI-Mtg-Prep.qmd' as an overview of the prep tasks. Now each task has its own qmd found in the prep folder and we are no longer using 'PAM-SI-Mtg-Prep.qmd' in the final output. 

Becca, you can see this change in the _quarto.yml file where line 38 has been commented out and replaced with the individual task files
https://github.com/SAEL-SWFSC/OpenScience/blob/30e78a92191f75f87ff4b6d299ff02d217e2d924/_quarto.yml#L36-L42

The changes you made in the [old prep file](content/PAM-SI-Mtg-Prep.qmd) should actually go in the new [step 4 file](content/prep/PAM-SI-Mtg-Prep-step4.qmd)

**Comment by Kourtney-Burger** [comment]
@rebecca-vanhoeck I was reviewing the changes you made and I want to clarify a couple things
https://github.com/SAEL-SWFSC/OpenScience/blob/30e78a92191f75f87ff4b6d299ff02d217e2d924/content/PAM-SI-Mtg-Prep.qmd#L60-L63

- As long as people have followed the first three pre meeting tasks (including cloning and making an r project), they should already have the PAM-SI-Mtg-March2024 directory open in their files window in Rstudio. This should allow them to easily open up the content folder and access the 'AttendeeIntros.qmd' file. 

https://github.com/SAEL-SWFSC/OpenScience/blob/30e78a92191f75f87ff4b6d299ff02d217e2d924/content/PAM-SI-Mtg-Prep.qmd#L64

- It sounds like you are pulling and pushing changes with git through Rstudio. While this is an option, we want to encourage people to use github desktop to do this. The desktop version is a little more beginner friendly and allows users to track and review their changes before commiting them. 

On the updated [step 4 file](https://github.com/SAEL-SWFSC/OpenScience/blob/30e78a92191f75f87ff4b6d299ff02d217e2d924/content/prep/PAM-SI-Mtg-Prep-step4.qmd#L1) there are more clear directions with pictures. Please review that and let me know if we need to add or explain anything further

**Comment by rebecca-vanhoeck** [comment]
Ah, thank you both for taking a look and Kourtney for figuring out my confusion. 

That clarification helps! I guess my issue was from switching between the open science and meeting repo. I also glazed over the github desktop sentence, since I was used to working only through RStudio. No need to move my edits to the updated step 4 file then. Thanks!
